
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-phase3
    restart: always
    environment:
      POSTGRES_DB: phase3_db_ecommerce
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    container_name: redis-phase3
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --requirepass 123456
    ports:
      - "6380:6379"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-phase3
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch-phase3
    restart: always
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  app:
    image: ecommerce-app:latest
    container_name: ecommerce-app
    restart: always
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      SHOW_SQL: ${SHOW_SQL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - elasticsearch

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  elasticsearch_data:
